### PR TITLE
[JENKINS-67452] Do not add blank external ids

### LINKED ISSUE #116: Jenkins is failing due to external Id is required in the latest release for IAM role
### Version report

Jenkins and plugins versions report:

```
aws-credentials:latest
```

- What Operating System are you using (both controller, and any agents involved in the problem)?

```
Linux
```

### Reproduction steps

- Step 1: Create a new credentials that will take an IAM role without external Id 

image

- Step 2: In the pipeline 

```
withCredentials([[$class       : 'AmazonWebServicesCredentialsBinding',
                                    credentialsId: credentials]])
```

### Results

Expected result:

Jenkins to grab the role and perform AWS tasks

Actual result:

com.amazonaws.services.securitytoken.model.AWSSecurityTokenServiceException: 1 validation error detected: Value '' at 'externalId' failed to satisfy constraint: Member must have length greater than or equal to 2 (Service: AWSSecurityTokenService

### PR DESCRIPTION
**Pull request by jtnord**
Fixes #116 

check the `externalId` is not blank or empty before adding it.

this covers the existing case where a credential was created before the externalId field was introduced (null) as well as after it was where it would be converted to an empty String (which is not a valid external id)

- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [x] Link to relevant issues in GitHub or Jira
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue

### CODE REVIEW

File: src/main/java/com/cloudbees/jenkins/plugins/awscredentials/AWSCredentialsImpl.java [hunk 1]
```diff
@@ -226,10 +226,13 @@ public String getDisplayName() {
     }
 
     private static AssumeRoleRequest createAssumeRoleRequest(String iamRoleArn, String iamExternalId) {
-        return new AssumeRoleRequest()
+        AssumeRoleRequest retval = new AssumeRoleRequest()
                 .withRoleArn(iamRoleArn)
-                .withExternalId(iamExternalId)
                 .withRoleSessionName("Jenkins");
+       if (iamExternalId.isEmpty()) {
```
Comment (jtnord) [inline src/main/java/com/cloudbees/jenkins/plugins/awscredentials/AWSCredentialsImpl.java:232]:
```suggestion
       if (iamExternalId != null && !iamExternalId.isEmpty()) {
```
