### PR TITLE
[JENKINS-58842] - Trim Jenkins name for Role Session Names to avoid issues with trailing spaces in localizations

### LINKED ISSUE #67: Error assuming IAM role in Jenkins (es_ES)
`Exception searching clusters for credentials=Test, regionName=eu-west-1:com.amazonaws.services.securitytoken.model.AWSSecurityTokenServiceException: 1 validation error detected: Value 'Jenkins ' at 'roleSessionName' failed to satisfy constraint: Member must satisfy regular expression pattern: [\w+=,.@-]* (Service: AWSSecurityTokenService; Status Code: 400; Error Code: ValidationError; Request ID: 20e28d0c-b8ff-11e9-8b33-4d7def127bc0)`

Looks like roleSessionName is wrong, as it includes a whitespace which breaks the assumeRole action. It doesn't happen in other languages. Forcing Jenkins to use en_GB locales (Using locale plugin for example) fixes it.

[This is the Jenkins file which contains the bad property](https://github.com/jenkinsci/jenkins/blob/master/core/src/main/resources/hudson/model/Messages_es.properties)

### PR DESCRIPTION
**Pull request by oleg-nenashev**
What could possibly go wrong when one uses a localized field for an AWS request session name? I have no idea why this field is used, maybe somebody overrides the "Jenkins" name in such way. I leave a full fix to the plugin maintainers who know the use-case, just fixing an obvious issue reported in https://issues.jenkins-ci.org/browse/JENKINS-58842

Fixes #67 

CC @diegombeltran

### CODE REVIEW

**Comment by oleg-nenashev** [comment]
https://github.com/jenkinsci/jenkins/pull/4145 for the fix on the core side

File: src/main/java/com/cloudbees/jenkins/plugins/awscredentials/AWSCredentialsImpl.java [hunk 1]
```diff
@@ -199,7 +199,7 @@ public String getDisplayName() {
     private static AssumeRoleRequest createAssumeRoleRequest(String iamRoleArn) {
         return new AssumeRoleRequest()
                 .withRoleArn(iamRoleArn)
-                .withRoleSessionName(Jenkins.getActiveInstance().getDisplayName());
+                .withRoleSessionName(Jenkins.getActiveInstance().getDisplayName().trim());
```
Comment (jglick) [inline src/main/java/com/cloudbees/jenkins/plugins/awscredentials/AWSCredentialsImpl.java]: There is no reason to localize this at all.

```suggestion
                .withRoleSessionName("Jenkins");
```

Comment (oleg-nenashev) [reply src/main/java/com/cloudbees/jenkins/plugins/awscredentials/AWSCredentialsImpl.java]: Up to maintainers, see the PR description

Comment (jglick) [reply src/main/java/com/cloudbees/jenkins/plugins/awscredentials/AWSCredentialsImpl.java]: AFAIK we just need to pass _something_ as the role session name, it does not really matter what; and since we cannot guarantee that a localization will match `[\w+=,.@-]*` even after trimming, it is not safe to use `Jenkins.displayName` at all.

Comment (escoem) [reply src/main/java/com/cloudbees/jenkins/plugins/awscredentials/AWSCredentialsImpl.java]: I agree, there is no reason for using the localized name but something as Jesse says.

**Comment by oleg-nenashev** [comment]
@escoem OK, integrated the change
